import Average from './Average';
import Colour from './Colour';
import DCT from './DCT';
import Difference from './Difference';
import handleImage from './handleImage';
import Perceptual from './Perceptual';
import phash from './phash';
import Resample from './Resample';
import similarity from './similarity';